### ISSUE TITLE
Devops - Analysis execute in seconds and nothing seems to be done. No errors but no results

### ISSUE THREAD

**Issue by tlogik** [a1dancole/OpenAI-Code-Review#1]
## Bug Description

I am testing your devops extension and i have discovered that i cannot actually get it to analyze anything.
It is unclear to me why.

I have setup a couple of pipelines, one for a C# based project and another with React (js, ts, html, css etc)

When the PR is triggers the pipeline the extension runs with success.
However the analysis take 1 second and then it is done.
There are no error messages or anything indicating a problem, but regardless of how many changes i add to a PR it does not seem to analyze them.

Can you asssist in figuring out why?

I have added a couple of screendumps from devops to show the result of the analysis as well as the YAML used.

## C# related pipeline
YAML
```yaml
      - job: CodeReview
        displayName: OPENAI - PR ONLY - Code Analysis
        condition: and(succeeded(), eq(variables.IS_PR, 'true'))
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - checkout: self
          persistCredentials: true
        - task: OpenAICodeReview@1
          inputs:
            api_key: $(OPENAI_APIKEY)
            ai_model: 'gpt-3.5-turbo'
            bugs: true
            performance: true
            best_practices: true
            file_extensions: 'cs,js,csproj'
            additional_prompts: 'Fix variable naming, Ensure consistent indentation, Review error handling approach'
```
Result (observe analysis is 1 second and nothing is added to the PR comments)

![devops-csharpproj-ai-pipelineresult](https://github.com/a1dancole/OpenAI-Code-Review/assets/5293103/8fb5f9c3-8e34-4063-9a1f-0eec2a2695f8)

## REACT related pipeline

YAML
```yaml
          - job: CodeReview
            displayName: OPENAI - PR ONLY - Code Analysis
            condition: and(succeeded(), eq(variables.IS_PR, 'true'))
            pool:
              vmImage: 'ubuntu-latest'
            steps:
            - checkout: self
              persistCredentials: true
            - task: OpenAICodeReview@1
              inputs:
                api_key: $(OPENAI_APIKEY)
                ai_model: 'gpt-3.5-turbo'
                bugs: true
                performance: true
                best_practices: true
                file_extensions: 'cs,js,html,css,ts'
                additional_prompts: 'Fix variable naming, Ensure consistent indentation, Review error handling approach'
```

Result (observe analysis is 1 second and nothing is added to the PR comments)

![devops-reactproj-ai-pipelineresult](https://github.com/a1dancole/OpenAI-Code-Review/assets/5293103/ab82fabe-376c-4794-9807-f0d0980f79e5)

## Extension version
- Version: 1.0.0 (Latest) Last updated 11 Dec 2023 at 14.58 CET

**Comment by a1dancole** [comment]
HI,

Thanks for trying out the extension.

I think it's because you've followed the documentation correctly! The extensions should actually be listed with a '.'

For example:

`      - job: CodeReview
        displayName: OPENAI - PR ONLY - Code Analysis
        condition: and(succeeded(), eq(variables.IS_PR, 'true'))
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - checkout: self
          persistCredentials: true
        - task: OpenAICodeReview@1
          inputs:
            api_key: $(OPENAI_APIKEY)
            ai_model: 'gpt-3.5-turbo'
            bugs: true
            performance: true
            best_practices: true
            file_extensions: '.cs,.js,.csproj'
            additional_prompts: 'Fix variable naming, Ensure consistent indentation, Review error handling approach'`

I'll get the tooltip updated, but that should get you working in the meantime. If not please let me know and I'll try and reproduce.

**Comment by tlogik** [comment]
Hi @a1dancole 
Thanks - that makes sense - I will test.
Then to follow up on the that area.
Does the EXCLUDE file list support wildcards?
example:
`'*.txt,*.css,*.bicep,*.yaml'`

**Comment by tlogik** [comment]
Hi @a1dancole 

I updated my pipeline task as you suggested and it works :-) 
Awesome - thanks for the support.
One comment to you documentation.
Maybe add the part of ensuring access to the AUTH token for YAML pipelines is achieved by this task:

```yaml
        - checkout: self
          persistCredentials: true
```
For brevity the updated YAML that works.

```yaml
      - job: CodeReview
        displayName: OPENAI - PR ONLY - Code Analysis
        condition: and(succeeded(), eq(variables.IS_PR, 'true'))
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - checkout: self
          persistCredentials: true
        - task: OpenAICodeReview@1
          inputs:
            api_key: '$(OPENAI_APIKEY)'
            ai_model: 'gpt-3.5-turbo'
            bugs: true
            performance: true
            best_practices: true
            file_extensions: '.cs,.js,.csproj'
            additional_prompts: 'Fix variable naming, Ensure consistent indentation, Review error handling approach'
```
