### ISSUE TITLE
Support Azure Pipeline

### ISSUE THREAD

**Issue by HakanKaraoglu** [a1dancole/OpenAI-Code-Review#12]
Hi, I am using a configuration like the one below, but as you can see in the images, the step is completed and it does not show me any suggestions. I could not understand where the problem is?

## Bug Description

Open AI step not working

```
- task: OpenAICodeReview@1
  inputs:
    api_key: '$(OPENAI_APIKEY)'
    ai_model: 'gpt-3.5-turbo'
    bugs: true
    performance: true
    best_practices: true
    file_extensions: '.cs,.js,.csproj'
    additional_prompts: 'Fix variable naming, Ensure consistent indentation, Review error handling approach'
```

## Screenshots

<img width="308" alt="image" src="https://github.com/user-attachments/assets/e466b940-9fbe-41c3-a936-535c4b0316da">
<img width="916" alt="image" src="https://github.com/user-attachments/assets/0a26c7f3-1476-44fe-a1e4-5b4d1bc2e0e5">
