### ISSUE TITLE
Unexpected token ;

### ISSUE THREAD

**Issue by jcbelmontes** [a1dancole/OpenAI-Code-Review#9]
## Bug Description

Unexpected token ';' message gets thrown when pipeline reaches the Open AI Step.

## Steps to Reproduce

1. Set OpenAI step 
```
- task: OpenAICodeReview@1
    inputs:
      api_key: $(OpenAI_ApiKey)
      ai_model: 'gpt-3.5-turbo'
      bugs: true
      performance: true
      best_practices: true
```
3. Run Pipeline
4. Wait for step to fail

## Expected Behavior

Code Review analysis should be done

## Actual Behavior

Step Open AI Code Review fails with message :  
> Unexpected token ;

## Environment Information

- Version: [1.0.0]

## Additional Information

Build Server OS: Windows Server 2019 64-bit
